[package]
name = "ferris-rgb-core"
version = "0.1.0"
edition = "2024"

[features]
pi = ["rpi-led-matrix"]

[target.'cfg(target_arch = "arm")'.dependencies]
rpi-led-matrix = { version = "0.4.0", optional = true }

[dependencies]


[dev-dependencies]
