[package]
name = "ferris-rgb-nats"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = "0.45.0"
bytes = "1.11.0"
futures-util = "0.3.31"
tokio = { version = "1.48.0", features = ["full"] }
